-- Run this SQL in Supabase SQL Editor to create OTP table

-- Create email_otp table for storing verification codes
CREATE TABLE IF NOT EXISTS public.email_otp (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  otp TEXT NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  verified BOOLEAN DEFAULT false,
  verified_at TIMESTAMP WITH TIME ZONE,
  failed_attempts INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.email_otp ENABLE ROW LEVEL SECURITY;

-- Policy: Anyone can insert (for registration)
CREATE POLICY "Allow insert for email_otp" ON public.email_otp
  FOR INSERT TO anon, authenticated WITH CHECK (true);

-- Policy: Anyone can select (for verification)
CREATE POLICY "Allow select for email_otp" ON public.email_otp
  FOR SELECT TO anon, authenticated USING (true);

-- Policy: Anyone can update (for verification)
CREATE POLICY "Allow update for email_otp" ON public.email_otp
  FOR UPDATE TO anon, authenticated USING (true);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_email_otp_email ON public.email_otp(email);